name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install setuptools, wheel, and twine
      run: python -m pip install setuptools wheel twine
    - name: Build distribution
      run: python setup.py sdist bdist_wheel
    - name: Publish the distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
